{
 "title": "reth",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(up)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage checkpoints",
   "type": "bargauge",
   "description": "The checkpoints mark the last block a stage can recover from in the case of a crash or shutdown of the node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "reth_sync_checkpoint{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Sync progress (stage progress in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_sync_entities_processed{instance=~\"$instance\"} / reth_sync_entities_total{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Sync progress (stage progress as highest block number reached)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "reth_sync_checkpoint{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "instance" },
  {
   "title": "Average commit time",
   "type": "timeseries",
   "description": "The average commit time for database transactions. Generally, this should not be a limiting factor in syncing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(reth_database_transaction_close_duration_seconds_sum{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval]) / rate(reth_database_transaction_close_duration_seconds_count{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval]) >= 0)",
     "legendFormat": "Commit time"
    }
   ]
  },
  {
   "title": "Commit time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg(avg_over_time(reth_database_transaction_close_duration_seconds{instance=~\"$instance\", outcome=\"commit\"}[$__interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Average transaction open time",
   "type": "timeseries",
   "description": "The average time a database transaction was open.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(reth_database_transaction_open_duration_seconds_sum{instance=~\"$instance\", outcome!=\"\"}[$__rate_interval]) / rate(reth_database_transaction_open_duration_seconds_count{instance=~\"$instance\", outcome!=\"\"}[$__rate_interval])) by (outcome, mode)",
     "legendFormat": "{{mode}}, {{outcome}}"
    }
   ]
  },
  {
   "title": "Max transaction open time",
   "type": "timeseries",
   "description": "The maximum time the database transaction was open.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_database_transaction_open_duration_seconds{instance=~\"$instance\", outcome!=\"\", quantile=\"1\"}[$__interval])) by (outcome, mode)",
     "legendFormat": "{{mode}}, {{outcome}}"
    }
   ]
  },
  {
   "title": "Number of open transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(reth_database_transaction_open_total{instance=~\"$instance\"}) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Max insertion operation time",
   "type": "timeseries",
   "description": "The maximum time the database transaction operation which inserts a large value took.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_database_operation_large_value_duration_seconds{instance=~\"$instance\", quantile=\"1\"}[$__interval]) > 0) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Database tables",
   "type": "piechart",
   "description": "The size of tables in the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_db_table_size{instance=~\"$instance\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Database growth",
   "type": "timeseries",
   "description": "The size of the database over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ( reth_db_table_size{instance=~\"$instance\"} )",
     "legendFormat": "Size ({{job}})"
    }
   ]
  },
  {
   "title": "Database pages",
   "type": "piechart",
   "description": "The type of the pages in the database:\n\n- **Leaf** pages contain KV pairs.\n- **Branch** pages contain information about keys in the leaf pages\n- **Overflow** pages store large values and should generally be avoided if possible",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) ( reth_db_table_pages{instance=~\"$instance\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overflow pages by table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sort_desc(reth_db_table_pages{instance=~\"$instance\", type=\"overflow\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Freelist",
   "type": "timeseries",
   "description": "The number of pages on the MDBX freelist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(reth_db_freelist{instance=~\"$instance\"}) by (job)",
     "legendFormat": "Pages ({{job}})"
    }
   ]
  },
  { "title": "Stage: Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }, "repeat": "instance" },
  {
   "title": "Gas processed",
   "type": "timeseries",
   "description": "The amount of gas processed by the execution stage in millions per second.\n\nNote: For mainnet, the block range 2,383,397-2,620,384 will be slow because of the 2016 DoS attack.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Mgas/s" } },
   "targets": [
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "Gas/s (30s)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Gas/s (1m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Gas/s (5m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[10m])",
     "legendFormat": "Gas/s (10m)"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "repeat": "instance" },
  {
   "title": "Discovery: Tracked peers",
   "type": "timeseries",
   "description": "The number of tracked peers in the discovery modules (dnsdisc and discv4)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "reth_network_tracked_peers{instance=~\"$instance\"}",
     "legendFormat": "Tracked peers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The number of incoming and outgoing connections, as well as the number of peers we are currently connected to. Outgoing and incoming connections also count peers we are trying to connect to.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "reth_network_outgoing_connections{instance=~\"$instance\"}",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "reth_network_incoming_connections{instance=~\"$instance\"}",
     "legendFormat": "Incoming connections"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  {
   "title": "P2P errors",
   "type": "timeseries",
   "description": "Internal errors in the P2P module. These are expected to happen from time to time. High error rates should not cause alarm if the node is peering otherwise.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_p2pstream_disconnected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "P2P stream disconnected"
    },
    {
     "expr": "rate(reth_network_pending_session_failures{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Failed pending sessions"
    },
    {
     "expr": "rate(reth_network_invalid_messages_received{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid messages"
    }
   ]
  },
  {
   "title": "Peer disconnect reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_network_useless_peer{instance=~\"$instance\"}",
     "legendFormat": "UselessPeer"
    },
    {
     "expr": "reth_network_subprotocol_specific{instance=~\"$instance\"}",
     "legendFormat": "SubprotocolSpecific"
    },
    {
     "expr": "reth_network_already_connected{instance=~\"$instance\"}",
     "legendFormat": "AlreadyConnected"
    },
    {
     "expr": "reth_network_client_quitting{instance=~\"$instance\"}",
     "legendFormat": "ClientQuitting"
    },
    {
     "expr": "reth_network_unexpected_identity{instance=~\"$instance\"}",
     "legendFormat": "UnexpectedHandshakeIdentity"
    },
    {
     "expr": "reth_network_disconnect_requested{instance=~\"$instance\"}",
     "legendFormat": "DisconnectRequested"
    },
    {
     "expr": "reth_network_null_node_identity{instance=~\"$instance\"}",
     "legendFormat": "NullNodeIdentity"
    },
    {
     "expr": "reth_network_tcp_subsystem_error{instance=~\"$instance\"}",
     "legendFormat": "TCPSubsystemError"
    },
    {
     "expr": "reth_network_incompatible{instance=~\"$instance\"}",
     "legendFormat": "IncompatibleP2PVersion"
    },
    {
     "expr": "reth_network_protocol_breach{instance=~\"$instance\"}",
     "legendFormat": "ProtocolBreach"
    },
    {
     "expr": "reth_network_too_many_peers{instance=~\"$instance\"}",
     "legendFormat": "TooManyPeers"
    }
   ]
  },
  {
   "title": "Total Dial Success",
   "type": "timeseries",
   "description": "Number of dials that resulted in a peer being added to the peerset",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 84 },
   "targets": [
    {
     "expr": "reth_network_total_dial_successes{instance=~\"$instance\"}",
     "legendFormat": "Total Dial Successes"
    }
   ]
  },
  { "title": "Downloader: Headers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }, "repeat": "instance" },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_total_downloaded{instance=~\"$instance\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_headers_total_flushed{instance=~\"$instance\"}",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_downloaded{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_flushed{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Flushed/s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the header downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_downloaders_headers_timeout_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "rate(reth_downloaders_headers_unexpected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "rate(reth_downloaders_headers_validation_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for headers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_in_flight_requests{instance=~\"$instance\"}",
     "legendFormat": "In flight requests"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  { "title": "Downloader: Bodies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 }, "repeat": "instance" },
  {
   "title": "I/O",
   "type": "timeseries",
   "description": "The internal state of the headers downloader: the number of downloaded headers, and the number of headers sent to the header stage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_total_downloaded{instance=~\"$instance\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_bodies_total_flushed{instance=~\"$instance\"}",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_flushed{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Flushed/s"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_downloaded{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_responses{instance=~\"$instance\"}",
     "legendFormat": "Buffered responses"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    },
    {
     "expr": "reth_downloaders_bodies_queued_blocks{instance=~\"$instance\"}",
     "legendFormat": "Queued blocks"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the bodies downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_downloaders_bodies_timeout_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "rate(reth_downloaders_bodies_unexpected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "rate(reth_downloaders_bodies_validation_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for bodies.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_in_flight_requests{instance=~\"$instance\"}",
     "legendFormat": "In flight requests"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  {
   "title": "Downloader buffer",
   "type": "timeseries",
   "description": "The number of blocks and size in bytes of those blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_buffered_blocks_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks size "
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    }
   ]
  },
  { "title": "Transaction Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }, "repeat": "instance" },
  {
   "title": "Subpool sizes in bytes",
   "type": "timeseries",
   "description": "Tracks a heuristic of the memory footprint of the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Base fee pool size"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Pending pool size"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Queued pool size"
    }
   ]
  },
  {
   "title": "Subpool transaction count",
   "type": "timeseries",
   "description": "Tracks the number of transactions in the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Base fee pool transactions"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Pending pool transactions"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Queued pool transactions"
    }
   ]
  },
  {
   "title": "Block body response sizes",
   "type": "timeseries",
   "description": "The number of blocks in a request and size in bytes of those block responses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_response_response_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Response size"
    },
    {
     "expr": "reth_downloaders_bodies_response_response_length{instance=~\"$instance\"}",
     "legendFormat": "Individual response length"
    },
    {
     "expr": "reth_downloaders_bodies_response_response_size_bytes / reth_downloaders_bodies_response_response_length",
     "legendFormat": "Mean body size in response"
    }
   ]
  },
  {
   "title": "Pending pool imports",
   "type": "timeseries",
   "description": "Number of transactions about to be imported into the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "reth_network_pending_pool_imports{instance=~\"$instance\"}",
     "legendFormat": "Transactions pending import"
    }
   ]
  },
  {
   "title": "Inflight Transaction Requests",
   "type": "timeseries",
   "description": "Currently active outgoing GetPooledTransactions requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "reth_network_inflight_transaction_requests{instance=~\"$instance\"}",
     "legendFormat": "Inflight Transaction Requests"
    }
   ]
  },
  {
   "title": "Inserted transactions",
   "type": "timeseries",
   "description": "Tracks the number of transactions inserted and removed from the transaction pool, as well as the number of invalid transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "increase(reth_transaction_pool_inserted_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Inserted transactions"
    },
    {
     "expr": "increase(reth_transaction_pool_removed_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Removed transactions"
    },
    {
     "expr": "increase(reth_transaction_pool_invalid_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid transactions"
    }
   ]
  },
  {
   "title": "Network transaction channel",
   "type": "timeseries",
   "description": "Tracks the number of transaction messages in the channel from the network to the transaction pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "increase(reth_network_pool_transactions_messages_sent{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "increase(reth_network_pool_transactions_messages_received{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Rx"
    },
    {
     "expr": "reth_network_pool_transactions_messages_sent{instance=~\"$instance\"} - reth_network_pool_transactions_messages_received{instance=~\"$instance\"}",
     "legendFormat": "Messages in channel"
    }
   ]
  },
  {
   "title": "Blob store",
   "type": "timeseries",
   "description": "Tracks the entries, byte size, failed inserts and file deletes of the blob store",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "targets": [
    {
     "expr": "reth_transaction_pool_blobstore_entries{instance=~\"$instance\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "reth_transaction_pool_blobstore_byte_size{instance=~\"$instance\"}",
     "legendFormat": "Bytesize"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_inserts{instance=~\"$instance\"}",
     "legendFormat": "Failed Inserts"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_deletes{instance=~\"$instance\"}",
     "legendFormat": "Failed Deletes"
    }
   ]
  },
  { "title": "Blockchain Tree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 }, "repeat": "instance" },
  {
   "title": "Canonical chain height",
   "type": "timeseries",
   "description": "The block number of the tip of the canonical chain from the blockchain tree.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_canonical_chain_height{instance=~\"$instance\"}",
     "legendFormat": "Canonical chain height"
    }
   ]
  },
  {
   "title": "Block buffer blocks",
   "type": "timeseries",
   "description": "Total number of blocks in the tree's block buffer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_block_buffer_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    }
   ]
  },
  {
   "title": "Sidechains",
   "type": "timeseries",
   "description": "Total number of sidechains in the blockchain tree",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_sidechains{instance=~\"$instance\"}",
     "legendFormat": "Total number of sidechains"
    }
   ]
  },
  {
   "title": "Canonical Commit Latency time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_consensus_engine_beacon_make_canonical_committed_latency_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_consensus_engine_beacon_make_canonical_committed_latency_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Engine API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 }, "repeat": "instance" },
  {
   "title": "Active block downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_active_block_downloads{instance=~\"$instance\"}",
     "legendFormat": "Active block downloads"
    }
   ]
  },
  {
   "title": "Engine API messages",
   "type": "timeseries",
   "description": "Engine API messages received by the CL, either engine_newPayload or engine_forkchoiceUpdated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_forkchoice_updated_messages{instance=~\"$instance\"}",
     "legendFormat": "Forkchoice updated messages"
    },
    {
     "expr": "reth_consensus_engine_beacon_new_payload_messages{instance=~\"$instance\"}",
     "legendFormat": "New payload messages"
    }
   ]
  },
  {
   "title": "Pipeline runs",
   "type": "timeseries",
   "description": "Total pipeline runs triggered by the sync controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_pipeline_runs{instance=~\"$instance\"}",
     "legendFormat": "Pipeline runs"
    }
   ]
  },
  { "title": "Payload Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 }, "repeat": "instance" },
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "description": "Number of active jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "targets": [
    {
     "expr": "reth_payloads_active_jobs{instance=~\"$instance\"}",
     "legendFormat": "Active Jobs"
    }
   ]
  },
  {
   "title": "Initiated Jobs",
   "type": "timeseries",
   "description": "Total number of initiated jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "targets": [
    {
     "expr": "reth_payloads_initiated_jobs{instance=~\"$instance\"}",
     "legendFormat": "Initiated Jobs"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "timeseries",
   "description": "Total number of failed jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "targets": [
    {
     "expr": "reth_payloads_failed_jobs{instance=~\"$instance\"}",
     "legendFormat": "Failed Jobs"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 } },
  {
   "title": "Jemalloc Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_jemalloc_active{instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "reth_jemalloc_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "reth_jemalloc_mapped{instance=~\"$instance\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "reth_jemalloc_metadata{instance=~\"$instance\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "reth_jemalloc_resident{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "reth_jemalloc_retained{instance=~\"$instance\"}",
     "legendFormat": "Retained"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "100% = 1 core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(reth_process_cpu_seconds_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "Open"
    }
   ]
  },
  { "title": "Pruning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 227 } },
  {
   "title": "Pruner duration, total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_pruner_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_pruner_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pruner duration, per segment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_pruner_segments_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_pruner_segments_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  { "title": "RPC server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 236 } },
  {
   "title": "Active Requests",
   "type": "graph",
   "description": "The number of active requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reth_rpc_server_requests_started{instance=~\"$instance\"} - reth_rpc_server_requests_finished{instance=~\"$instance\"}",
     "legendFormat": "Active Requests"
    }
   ]
  },
  {
   "title": "Active Websocket Connections",
   "type": "graph",
   "description": "The number of active websocket connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reth_rpc_server_ws_session_opened{instance=~\"$instance\"} - reth_rpc_server_ws_session_closed{instance=~\"$instance\"}",
     "legendFormat": "Active Websocket Connections"
    }
   ]
  },
  {
   "title": "Request Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
   "targets": [
    {
     "expr": "sum(increase(reth_rpc_server_request_latency{instance=~\"$instance\"}[$__rate_interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Call Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
   "targets": [
    {
     "expr": "sum(increase(reth_rpc_server_call_latency{instance=~\"$instance\"}[$__rate_interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Database - Canonicalization Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 253 },
   "repeat": "instance"
  },
  {
   "title": "Insert Storage Hashing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert storage hashing\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Account Hashing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 254 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert account hashing\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Merkle Tree",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 262 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert merkle tree\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Block",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 262 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert block\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert State",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert state\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Hashes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 270 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert hashes\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert History Indices",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 278 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert history indices\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Update Pipeline Stages",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 278 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"update pipeline stages\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Canonical Headers",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 286 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert canonical headers\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Headers",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 286 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert headers\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Header Numbers",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 294 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert header numbers\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Header TD",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 294 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert header TD\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Block Ommers",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 302 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert block ommers\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Tx Senders",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 302 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert tx senders\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Transactions",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 310 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert transactions\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Tx Hash Numbers",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 310 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert tx hash numbers\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Block Withdrawals",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 318 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert block withdrawals\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Block Indices",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 318 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert block body indices\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Transaction Block",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 326 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"insert transaction block\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Recover Signers",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 326 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"recover signers\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Get Next Tx Num",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 334 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"get next tx num\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Get Parent TD",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 334 },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{action=\"get parent TD\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Blockchain Tree - Canonicalization Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 342 },
   "repeat": "instance"
  },
  {
   "title": "Clone Old Blocks",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 343 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"clone old blocks\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Find Canonical Header",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 343 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"find canonical header\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Split Chain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 351 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"split chain\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Split Chain Forks",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 351 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"split chain forks\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Merge All Chains",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 359 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"merge all chains\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Update Canonical Index",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 359 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"update canonical index\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Commit Canonical Chain To Database",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 367 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"commit canonical chain to database\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Revert Canonical Chain From Database",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 367 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"revert canonical chain from database\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Insert Old Canonical Chain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 375 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{action=\"insert old canonical chain\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}